/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Negocio.CategoriaVIP;
import javax.swing.JOptionPane;

/**
 *
 * @author 00161615
 */
public class DistribuicaoCategoria extends javax.swing.JFrame {

    /**
     * Creates new form DistribuicaoCategoria
     */
    private ClntGUI clienteGUI;
    public DistribuicaoCategoria(ClntGUI clntGUI) {
        initComponents();
        clienteGUI = clntGUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonValidar = new javax.swing.JButton();
        jTextFieldSILVER = new javax.swing.JTextField();
        jTextFieldGOLD = new javax.swing.JTextField();
        jTextFieldPLATINUM = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(CategoriaVIP.values())
        );

        jLabel1.setText("Categoria");

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabel2.setText("Clientes VIP com categoria SILVER");

        jLabel3.setText("Clientes VIP com categoria GOLD");

        jLabel4.setText("Clientes VIP com categoria PLATINUM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldSILVER, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jButtonValidar)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVoltar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldPLATINUM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                    .addComponent(jTextFieldGOLD, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonValidar))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSILVER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGOLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPLATINUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        int total;
       int calculo;
       total = clienteGUI.totalClientes();
               //clienteGUI.quantidadeClientesCategoria("SILVER") + clienteGUI.quantidadeClientesCategoria("GOLD") + clienteGUI.quantidadeClientesCategoria("PLATINUM");
        if(((CategoriaVIP)jComboBoxCategoria.getSelectedItem()).toString().equals("VAZIO")){
            calculo = 100 * clienteGUI.quantidadeClientesCategoria("SILVER");
            calculo = calculo / total;
            jTextFieldSILVER.setText(calculo + "%");
            calculo = 100 * clienteGUI.quantidadeClientesCategoria("GOLD");
            calculo = calculo / total;
            jTextFieldGOLD.setText(calculo + "%");
            calculo = 100 * clienteGUI.quantidadeClientesCategoria("PLATINUM");
            calculo = calculo / total;
            jTextFieldPLATINUM.setText(calculo + "%");
        }
        else if(((CategoriaVIP)jComboBoxCategoria.getSelectedItem()).toString().equals("SILVER")){
             calculo = 100 * clienteGUI.quantidadeClientesCategoria("SILVER");
            calculo = calculo / total;
            jTextFieldSILVER.setText(calculo + "%");
        }
        else if(((CategoriaVIP)jComboBoxCategoria.getSelectedItem()).toString().equals("GOLD")){
            calculo = 100 * clienteGUI.quantidadeClientesCategoria("GOLD");
            calculo = calculo / total;
            jTextFieldGOLD.setText(calculo + "%");
        }
        else if(((CategoriaVIP)jComboBoxCategoria.getSelectedItem()).toString().equals("PLATINUM")){
            calculo = 100 * clienteGUI.quantidadeClientesCategoria("PLATINUM");
            calculo = calculo / total;
            jTextFieldPLATINUM.setText(calculo + "%");
        }       
       // TODO add your handling code here:
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldGOLD;
    private javax.swing.JTextField jTextFieldPLATINUM;
    private javax.swing.JTextField jTextFieldSILVER;
    // End of variables declaration//GEN-END:variables
}
