/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Negocio.BarException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 00161615
 */

public class DistribuicaoGenero extends javax.swing.JFrame {

    /**
     * Creates new form DistribuicaoGenero
     */
    
    private CtrlGUI clienteGUI;
    
    public DistribuicaoGenero(CtrlGUI clntGUI) {
        initComponents();
        clienteGUI = clntGUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPercentualMasculino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPercentualFeminino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonValidar = new javax.swing.JButton();
        jButtonVariavel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clientes do Sexo Masculino Presentes");

        jLabel2.setText("Clientes do Sexo Feminino Presentes");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Masculino", "Feminino" }));

        jLabel3.setText("Sexo");

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        jButtonVariavel.setText("Voltar");
        jButtonVariavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVariavelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonValidar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPercentualFeminino, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPercentualMasculino))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(jButtonVariavel))
                        .addGap(0, 157, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonValidar))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPercentualMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPercentualFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButtonVariavel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
       int total;
       int calculo;
       total = clienteGUI.quantidadeClientesGenero("Masculino") + clienteGUI.quantidadeClientesGenero("Feminino");
        if(jComboBoxGenero.getSelectedIndex()==0){
            calculo = 100 * clienteGUI.quantidadeClientesGenero("Masculino");
            calculo = calculo / total;
            jTextFieldPercentualMasculino.setText(calculo + "%");
            calculo = 100 * clienteGUI.quantidadeClientesGenero("Feminino");
            calculo = calculo / total;
            jTextFieldPercentualFeminino.setText(calculo + "%");
        }
        else if(jComboBoxGenero.getSelectedIndex()==1){
            calculo = 100 * clienteGUI.quantidadeClientesGenero("Masculino");
            calculo = calculo / total;
            jTextFieldPercentualMasculino.setText(calculo + "%");
        }
        else if(jComboBoxGenero.getSelectedIndex()==2){
            calculo = 100 * clienteGUI.quantidadeClientesGenero("Feminino");
            calculo = calculo / total;
            jTextFieldPercentualFeminino.setText(calculo + "%");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonVariavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVariavelActionPerformed
       dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVariavelActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonVariavel;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldPercentualFeminino;
    private javax.swing.JTextField jTextFieldPercentualMasculino;
    // End of variables declaration//GEN-END:variables
}
