/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Negocio.BarException;
import Persistencia.DAOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author 00161615
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaBar
     */
    private ClntGUI clntGUI;
    private String categoria;
    private String tipoCliente;
    private String sexo;

    public Principal() {

        initComponents();

        try {
            clntGUI = new ClntGUI();
        } catch (BarException ex) {
            JOptionPane.showMessageDialog(null, "Falha de inicialização. " + ex.getMessage());
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jButton4 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMIRegistrarEntrada = new javax.swing.JMenuItem();
        jMIRegistrarSaida = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMIListarCliente = new javax.swing.JMenuItem();
        jMIListarClientePorGenero = new javax.swing.JMenuItem();
        jMIListaClientePorCategoria = new javax.swing.JMenuItem();
        jMIDistribuicaoPorGenero = new javax.swing.JMenuItem();
        jMIDistribuicaoPorCategoria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setText("SAIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("Registrar");

        jMIRegistrarEntrada.setText("Registrar Entrada");
        jMIRegistrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistrarEntradaActionPerformed(evt);
            }
        });
        jMenu1.add(jMIRegistrarEntrada);

        jMIRegistrarSaida.setText("Registrar Saida");
        jMIRegistrarSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistrarSaidaActionPerformed(evt);
            }
        });
        jMenu1.add(jMIRegistrarSaida);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Pesquisar");

        jMIListarCliente.setText("Listar Cliente");
        jMIListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMIListarCliente);

        jMIListarClientePorGenero.setText("Listar Clientes Por Genero");
        jMIListarClientePorGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListarClientePorGeneroActionPerformed(evt);
            }
        });
        jMenu2.add(jMIListarClientePorGenero);

        jMIListaClientePorCategoria.setText("Listar Clientes Por Categoria");
        jMIListaClientePorCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListaClientePorCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMIListaClientePorCategoria);

        jMIDistribuicaoPorGenero.setText("Distribuição de Clientes Por Genero");
        jMIDistribuicaoPorGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDistribuicaoPorGeneroActionPerformed(evt);
            }
        });
        jMenu2.add(jMIDistribuicaoPorGenero);

        jMIDistribuicaoPorCategoria.setText("Distribuição de Clientes Por Categoria");
        jMIDistribuicaoPorCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDistribuicaoPorCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMIDistribuicaoPorCategoria);

        jMenuBar2.add(jMenu2);

        jMenu3.setText("Opções");

        jMenuItem5.setText("Sair");
        jMenu3.add(jMenuItem5);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMIListarClientePorGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListarClientePorGeneroActionPerformed
        ListaClientePorSexo listaPSexo = new ListaClientePorSexo(clntGUI);
        listaPSexo.setVisible(true);
    }//GEN-LAST:event_jMIListarClientePorGeneroActionPerformed

    private void jMIRegistrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistrarEntradaActionPerformed
        CadastroCliente cadClnt = new CadastroCliente(clntGUI);
        cadClnt.setVisible(true);
    }//GEN-LAST:event_jMIRegistrarEntradaActionPerformed

    private void jMIRegistrarSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistrarSaidaActionPerformed
        RegistraSaida regSaida = new RegistraSaida(clntGUI);
        regSaida.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIRegistrarSaidaActionPerformed

    private void jMIListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListarClienteActionPerformed
        try {
            ListModel clientes = clntGUI.getClientes();
            ListaClientes dSel = new ListaClientes(this, true, clientes);
            dSel.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Falha na busca. " + e.getMessage());
        }
    }//GEN-LAST:event_jMIListarClienteActionPerformed

    private void jMIListaClientePorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListaClientePorCategoriaActionPerformed

        ListaClientePorCategoria listaPCategoria = new ListaClientePorCategoria(clntGUI);
        listaPCategoria.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIListaClientePorCategoriaActionPerformed

    private void jMIDistribuicaoPorGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDistribuicaoPorGeneroActionPerformed
        DistribuicaoGenero dClntG = new DistribuicaoGenero(clntGUI);
        dClntG.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIDistribuicaoPorGeneroActionPerformed

    private void jMIDistribuicaoPorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDistribuicaoPorCategoriaActionPerformed
        DistribuicaoCategoria distribuiClntCategoria = new DistribuicaoCategoria(clntGUI);
        distribuiClntCategoria.setVisible(true);
    }//GEN-LAST:event_jMIDistribuicaoPorCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JMenuItem jMIDistribuicaoPorCategoria;
    private javax.swing.JMenuItem jMIDistribuicaoPorGenero;
    private javax.swing.JMenuItem jMIListaClientePorCategoria;
    private javax.swing.JMenuItem jMIListarCliente;
    private javax.swing.JMenuItem jMIListarClientePorGenero;
    private javax.swing.JMenuItem jMIRegistrarEntrada;
    private javax.swing.JMenuItem jMIRegistrarSaida;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
